/**
 * Receipt Wrangler API.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provenance status for the receipt\'s effective base-currency amount
 */
export type FxStatus = 'DOMESTIC' | 'ESTIMATED' | 'CONFIRMED' | 'NEEDS_REVIEW';

export const FxStatus = {
    Domestic: 'DOMESTIC' as FxStatus,
    Estimated: 'ESTIMATED' as FxStatus,
    Confirmed: 'CONFIRMED' as FxStatus,
    NeedsReview: 'NEEDS_REVIEW' as FxStatus
};
