/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMember } from './groupMember';
import { GroupReceiptSettings } from './groupReceiptSettings';
import { GroupStatus } from './groupStatus';
import { GroupSettings } from './groupSettings';


/**
 * Group in the system
 */
export interface Group { 
    createdAt?: string;
    createdBy?: number;
    groupSettings?: GroupSettings;
    groupReceiptSettings: GroupReceiptSettings;
    /**
     * Members of the group
     */
    groupMembers: Array<GroupMember>;
    id: number;
    /**
     * Is default group (not used yet)
     */
    isDefault?: boolean;
    /**
     * Name of the group
     */
    name: string;
    /**
     * Is all group for user
     */
    isAllGroup: boolean;
    /**
     * Whether member-presence isolation is enabled for the group. When on, members cannot discover other members unless they hold a group role flagged seesAllMembers. Defaults to false.
     */
    isolateMembers?: boolean;
    /**
     * ISO 4217 accounting currency used for effective receipt amounts
     */
    baseCurrencyCode: string;
    status: GroupStatus;
    updatedAt?: string;
}
export namespace Group {
}


