/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldValue } from './customFieldValue';
import { Group } from './group';
import { GroupMember } from './groupMember';
import { Category } from './category';
import { ReportRequestCommand } from './reportRequestCommand';
import { ReportTemplate } from './reportTemplate';
import { Activity } from './activity';
import { UserView } from './userView';
import { ReceiptProcessingSettings } from './receiptProcessingSettings';
import { Item } from './item';
import { GroupReceiptSettings } from './groupReceiptSettings';
import { SystemTaskStatus } from './systemTaskStatus';
import { OcrEngine } from './ocrEngine';
import { CustomFieldOption } from './customFieldOption';
import { SystemTask } from './systemTask';
import { GroupSettings } from './groupSettings';
import { TagView } from './tagView';
import { FileData } from './fileData';
import { Comment } from './comment';
import { Receipt } from './receipt';
import { CustomFieldType } from './customFieldType';
import { FxStatus } from './fxStatus';
import { AiType } from './aiType';
import { CustomField } from './customField';
import { AssociatedEntityType } from './associatedEntityType';
import { Prompt } from './prompt';
import { SystemEmail } from './systemEmail';
import { Tag } from './tag';


export interface PagedDataDataInner { 
    /**
     * Effective amount in the group\'s base currency
     */
    amount: string;
    /**
     * Original total printed on the receipt evidence
     */
    documentAmount: string;
    /**
     * ISO 4217 currency printed on the receipt evidence
     */
    documentCurrencyCode: string;
    /**
     * Historical-rate estimate in the group\'s base currency
     */
    estimatedBaseAmount?: string;
    /**
     * Exact document-to-base exchange rate used for the estimate
     */
    fxRate?: string;
    /**
     * Effective date returned by the FX provider
     */
    fxDate?: string;
    /**
     * Provider used for the historical estimate
     */
    fxProvider?: string;
    /**
     * UTC instant at which the rate was retrieved
     */
    fxRetrievedAt?: string;
    fxStatus: FxStatus;
    /**
     * Categories associated to receipt
     */
    categories: Array<Category>;
    /**
     * Comments associated to receipt
     */
    comments: Array<Comment>;
    /**
     * Custom fields associated to receipt
     */
    customFields: Array<CustomFieldValue>;
    createdAt: string;
    createdBy?: number;
    /**
     * Receipt date
     */
    date: string;
    groupId: number;
    id: number;
    /**
     * Files associated to receipt
     */
    imageFiles?: Array<FileData>;
    /**
     * The template name (mirrors the saved report\'s name).
     */
    name: string;
    /**
     * User paid foreign key
     */
    paidByUserId: number;
    /**
     * Items associated to receipt
     */
    receiptItems: Array<Item>;
    /**
     * Date resolved
     */
    resolvedDate?: string;
    status: SystemTaskStatus;
    /**
     * Tags associated to receipt
     */
    tags: Array<Tag>;
    updatedAt?: string;
    /**
     * Created by entity\'s name
     */
    createdByString?: string;
    /**
     * Custom Field description
     */
    description?: string;
    prompt: Prompt;
    groupSettings?: GroupSettings;
    groupReceiptSettings: GroupReceiptSettings;
    /**
     * Members of the group
     */
    groupMembers: Array<GroupMember>;
    /**
     * Is default group (not used yet)
     */
    isDefault?: boolean;
    /**
     * Is all group for user
     */
    isAllGroup: boolean;
    /**
     * Whether member-presence isolation is enabled for the group. When on, members cannot discover other members unless they hold a group role flagged seesAllMembers. Defaults to false.
     */
    isolateMembers?: boolean;
    /**
     * ISO 4217 accounting currency used for effective receipt amounts
     */
    baseCurrencyCode: string;
    /**
     * Number of receipts associated with this tag
     */
    numberOfReceipts: number;
    type: CustomFieldType;
    startedAt: string;
    endedAt: string;
    associatedEntityId?: number;
    associatedEntityType?: AssociatedEntityType;
    ranByUserId?: number;
    receiptId?: number;
    resultDescription?: string;
    apiKeyId?: string;
    childSystemTasks?: Array<SystemTask>;
    aiType?: AiType;
    /**
     * URL for custom endpoints
     */
    url?: string;
    /**
     * Key for endpoints that require authentication
     */
    key?: string;
    /**
     * LLM model
     */
    model?: string;
    /**
     * Is vision model
     */
    isVisionModel?: boolean;
    /**
     * Enforce JSON response format on the LLM provider. Disable if the provider does not support this flag.
     */
    enforceJsonResponseFormat?: boolean;
    ocrEngine?: OcrEngine;
    /**
     * Prompt foreign key
     */
    promptId?: number;
    /**
     * IMAP host
     */
    host?: string;
    /**
     * IMAP port
     */
    port?: string;
    /**
     * User\'s username used to login
     */
    username: string;
    /**
     * IMAP password
     */
    password?: string;
    /**
     * Whether to use STARTTLS
     */
    useStartTLS?: boolean;
    canBeRestarted?: boolean;
    options?: Array<CustomFieldOption>;
    configuration: ReportRequestCommand;
    /**
     * Schema version the stored configuration was written under.
     */
    configurationVersion: number;
    /**
     * The actions the requesting user may perform on this template (read, generate, update, delete, duplicate), resolved per user and populated only on the list response. Drives the row action buttons.
     */
    allowedActions?: Array<string>;
    /**
     * Default avatar color
     */
    defaultAvatarColor?: string;
    /**
     * Display name
     */
    displayName: string;
    /**
     * Is dummy user
     */
    isDummyUser: boolean;
    /**
     * Id of the modern app role assigned to the user
     */
    appRoleId?: number;
}
export namespace PagedDataDataInner {
}


