/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldValue } from './customFieldValue';
import { Comment } from './comment';
import { Item } from './item';
import { Category } from './category';
import { FxStatus } from './fxStatus';
import { ReceiptStatus } from './receiptStatus';
import { Tag } from './tag';
import { FileData } from './fileData';


/**
 * Receipt
 */
export interface Receipt { 
    /**
     * Effective amount in the group\'s base currency
     */
    amount: string;
    /**
     * Original total printed on the receipt evidence
     */
    documentAmount: string;
    /**
     * ISO 4217 currency printed on the receipt evidence
     */
    documentCurrencyCode: string;
    /**
     * Historical-rate estimate in the group\'s base currency
     */
    estimatedBaseAmount?: string;
    /**
     * Exact document-to-base exchange rate used for the estimate
     */
    fxRate?: string;
    /**
     * Effective date returned by the FX provider
     */
    fxDate?: string;
    /**
     * Provider used for the historical estimate
     */
    fxProvider?: string;
    /**
     * UTC instant at which the rate was retrieved
     */
    fxRetrievedAt?: string;
    fxStatus: FxStatus;
    /**
     * Categories associated to receipt
     */
    categories: Array<Category>;
    /**
     * Comments associated to receipt
     */
    comments: Array<Comment>;
    /**
     * Custom fields associated to receipt
     */
    customFields: Array<CustomFieldValue>;
    createdAt?: string;
    createdBy?: number;
    /**
     * Receipt date
     */
    date: string;
    /**
     * Group foreign key
     */
    groupId: number;
    id: number;
    /**
     * Files associated to receipt
     */
    imageFiles?: Array<FileData>;
    /**
     * Receipt name
     */
    name: string;
    /**
     * User paid foreign key
     */
    paidByUserId: number;
    /**
     * Items associated to receipt
     */
    receiptItems: Array<Item>;
    /**
     * Date resolved
     */
    resolvedDate?: string;
    status: ReceiptStatus;
    /**
     * Tags associated to receipt
     */
    tags: Array<Tag>;
    updatedAt?: string;
    /**
     * Created by string, which is anything that is not a user
     */
    createdByString?: string;
}
export namespace Receipt {
}


