/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SupplierProfile } from './supplierProfile';


export interface ResolveSupplierProfileResponse { 
    /**
     * Matching enabled profile, or null when none / ambiguous
     */
    profile?: SupplierProfile;
}

