/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FxStatus } from './fxStatus';
import { ReceiptStatus } from './receiptStatus';


export interface SearchResult { 
    id: number;
    name: string;
    type: string;
    groupId: number;
    date: string;
    /**
     * Effective amount in the group\'s base currency
     */
    amount: string;
    /**
     * Original total printed on the receipt evidence
     */
    documentAmount: string;
    /**
     * ISO 4217 currency printed on the receipt evidence
     */
    documentCurrencyCode: string;
    fxStatus: FxStatus;
    receiptStatus?: ReceiptStatus;
    paidByUserId?: number;
    createdAt: string;
}
export namespace SearchResult {
}


