/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpsertGroupMemberCommand } from './upsertGroupMemberCommand';
import { GroupStatus } from './groupStatus';


export interface UpsertGroupCommand { 
    /**
     * Members of the group
     */
    groupMembers: Array<UpsertGroupMemberCommand>;
    /**
     * Is default group (not used yet)
     */
    isDefault?: boolean;
    /**
     * Name of the group
     */
    name: string;
    /**
     * Is all group for user
     */
    isAllGroup?: boolean;
    /**
     * Whether to enable member-presence isolation for the group. When on, members cannot discover other members unless they hold a group role flagged seesAllMembers. Defaults to false.
     */
    isolateMembers?: boolean;
    /**
     * ISO 4217 accounting currency; defaults to AUD when omitted
     */
    baseCurrencyCode?: string;
    status: GroupStatus;
}
export namespace UpsertGroupCommand {
}


