/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FxStatus } from './fxStatus';
import { UpsertCategoryCommand } from './upsertCategoryCommand';
import { UpsertCustomFieldValueCommand } from './upsertCustomFieldValueCommand';
import { UpsertItemCommand } from './upsertItemCommand';
import { UpsertCommentCommand } from './upsertCommentCommand';
import { ReceiptStatus } from './receiptStatus';
import { UpsertTagCommand } from './upsertTagCommand';


export interface UpsertReceiptCommand { 
    /**
     * Receipt name
     */
    name: string;
    /**
     * Effective base-currency amount; required for compatibility and confirmed FX values
     */
    amount: string;
    /**
     * Original total printed on the receipt; defaults to amount when omitted
     */
    documentAmount?: string;
    /**
     * ISO 4217 currency printed on the receipt; defaults to the group base currency
     */
    documentCurrencyCode?: string;
    fxStatus?: FxStatus;
    /**
     * Receipt date
     */
    date: string;
    /**
     * Group foreign key
     */
    groupId: number;
    /**
     * User paid foreign key
     */
    paidByUserId: number;
    status: ReceiptStatus;
    /**
     * Categories associated to receipt
     */
    categories?: Array<UpsertCategoryCommand>;
    /**
     * Tags associated to receipt
     */
    tags?: Array<UpsertTagCommand>;
    /**
     * Items associated to receipt
     */
    receiptItems?: Array<UpsertItemCommand>;
    /**
     * Comments associated to receipt
     */
    comments?: Array<UpsertCommentCommand>;
    /**
     * Custom fields associated to receipt
     */
    customFields?: Array<UpsertCustomFieldValueCommand>;
}
export namespace UpsertReceiptCommand {
}


